const products=[
 {id:1,name:'Ensemble nuage en coton',age:'0-6',category:'0–6 mois',price:2890,cost:1450,stock:24,sku:'BMS-001',icon:'☁️',color:'#dceeff',badge:'Nouveau'},
 {id:2,name:'Doudou lapin douceur',age:'0-6',category:'Éveil & doudous',price:1950,cost:820,stock:5,sku:'BMS-002',icon:'🐰',color:'#ffe0e9',badge:'Best-seller'},
 {id:3,name:'Look mini aventurier',age:'6-18',category:'6–18 mois',price:4590,cost:2350,stock:0,sku:'BMS-003',icon:'🧢',color:'#e9e2cc',badge:'Été'},
 {id:4,name:'Coffret repas silicone',age:'6-18',category:'Repas',price:3750,cost:1800,stock:12,sku:'BMS-004',icon:'🥣',color:'#ffe4bb',badge:'Pratique'},
 {id:5,name:'Pyjama étoiles 2 pièces',age:'18-36',category:'18–36 mois',price:3490,cost:1620,stock:3,sku:'BMS-005',icon:'🌟',color:'#e5dbff',badge:'-15%'},
 {id:6,name:'Chaussures premiers pas',age:'18-36',category:'Chaussures',price:4250,cost:2190,stock:18,sku:'BMS-006',icon:'👟',color:'#d9f3e5',badge:'Confort'},
 {id:7,name:'Chapeau léger soleil',age:'season',category:'Collection été',price:1690,cost:690,stock:8,sku:'BMS-007',icon:'👒',color:'#ffe6b2',badge:'Été'},
 {id:8,name:'Tapis d’éveil safari',age:'0-6',category:'Éveil & doudous',price:8990,cost:4700,stock:2,sku:'BMS-008',icon:'🦁',color:'#d9eee3',badge:'Premium'}];
let cart=JSON.parse(localStorage.getItem('bms-cart')||'[]');let selectedCategory='all';
const dz=n=>new Intl.NumberFormat('fr-DZ').format(n)+' DZD';
function renderProductSkeleton(n){document.querySelector('#productGrid').innerHTML=Array(n||8).fill(0).map(()=>'<article class="product skeleton-card"><div class="product-image skel"></div><div class="product-info"><p class="skel skel-line" style="width:40%"></p><h3 class="skel skel-line" style="width:75%;height:15px"></h3><div class="product-bottom"><b class="skel skel-line" style="width:35%"></b></div></div></article>').join('')}
function renderProducts(){const q=document.querySelector('#searchInput').value.toLowerCase();const list=products.filter(p=>(selectedCategory==='all'||p.age===selectedCategory||(selectedCategory==='season'&&p.age==='season'))&&pname(p).toLowerCase().includes(q));document.querySelector('#productGrid').innerHTML=list.map(p=>`<article class="product"><div class="product-image" style="background:${p.color}" data-quickview="${p.id}" role="button" tabindex="0" aria-label="${pname(p)}"><span class="badge">${p.badge}</span>${p.icon}</div><div class="product-info"><p>${catLabel(p)}</p><h3 data-quickview="${p.id}" role="button" tabindex="0">${pname(p)}</h3><div class="product-bottom"><b>${dz(p.price)}</b><button class="add-btn" data-add="${p.id}" ${p.stock===0?'disabled title="'+t('quickview.outOfStock')+'"':''}>${p.stock===0?'×':'+'}</button></div></div></article>`).join('')||`<p>${t('products.empty')}</p>`;document.querySelectorAll('[data-quickview]').forEach(el=>{el.addEventListener('click',()=>openQuickView(el.dataset.quickview));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openQuickView(el.dataset.quickview)}})});document.querySelectorAll('[data-add]').forEach(btn=>btn.addEventListener('click',()=>addToCart(btn.dataset.add)))}
let qvId=null,qvQty=1;
function openQuickView(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;qvId=id;qvQty=1;document.querySelector('#qvMedia').innerHTML=`<div class="quickview-image" style="background:${p.color}"><span class="badge">${p.badge}</span>${p.icon}</div>`;document.querySelector('#qvCategory').textContent=catLabel(p);document.querySelector('#qvName').textContent=pname(p);document.querySelector('#qvDesc').textContent=p.description||t('quickview.defaultDesc');document.querySelector('#qvPrice').textContent=dz(p.price);document.querySelector('#qvQty').textContent=qvQty;const addBtn=document.querySelector('#qvAddBtn');const stockMsg=document.querySelector('#qvStockMsg');if(p.stock===0){addBtn.disabled=true;addBtn.textContent=t('quickview.outOfStock');stockMsg.textContent=t('quickview.restock')}else{addBtn.disabled=false;addBtn.textContent=t('quickview.add');stockMsg.textContent=p.stock<6?t('quickview.lowStock',{n:p.stock}):''}document.querySelector('#quickViewModal').classList.remove('hidden')}
function closeQuickView(){document.querySelector('#quickViewModal').classList.add('hidden')}
document.querySelector('#closeQuickView').addEventListener('click',closeQuickView);
document.querySelector('#quickViewModal').addEventListener('click',e=>{if(e.target.id==='quickViewModal')closeQuickView()});
document.querySelector('#qvMinus').addEventListener('click',()=>{if(qvQty>1){qvQty--;document.querySelector('#qvQty').textContent=qvQty}});
document.querySelector('#qvPlus').addEventListener('click',()=>{const p=products.find(x=>String(x.id)===String(qvId));if(p&&qvQty<p.stock){qvQty++;document.querySelector('#qvQty').textContent=qvQty}else toast(t('toast.maxQty'))});
document.querySelector('#qvAddBtn').addEventListener('click',()=>{const p=products.find(x=>String(x.id)===String(qvId));if(!p)return;const line=cart.find(x=>String(x.id)===String(qvId));if(line){line.qty=Math.min(p.stock,line.qty+qvQty)}else cart.push({id:qvId,qty:qvQty});saveCart();toast(t('toast.added'));closeQuickView()});
function addToCart(id){const p=products.find(p=>String(p.id)===String(id)),line=cart.find(x=>String(x.id)===String(id));if(line){if(line.qty<p.stock)line.qty++}else cart.push({id,qty:1});saveCart();toast(t('toast.added'))}
function saveCart(){localStorage.setItem('bms-cart',JSON.stringify(cart));document.querySelector('#cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0);renderCart()}
function renderCart(){const holder=document.querySelector('#cartItems');if(!holder)return;const lines=cart.map(x=>({...products.find(p=>String(p.id)===String(x.id)),qty:x.qty}));holder.innerHTML=lines.length?lines.map(p=>`<article class="cart-item"><div class="cart-icon" style="background:${p.color}">${p.icon}</div><div><h3>${pname(p)}</h3><p>${dz(p.price)} · ${catLabel(p)}</p></div><div class="qty"><button data-qty-minus="${p.id}">−</button><b>${p.qty}</b><button data-qty-plus="${p.id}">+</button></div></article>`).join(''):`<p>${t('cart.empty')}</p>`;holder.querySelectorAll('[data-qty-minus]').forEach(b=>b.addEventListener('click',()=>changeQty(b.dataset.qtyMinus,-1)));holder.querySelectorAll('[data-qty-plus]').forEach(b=>b.addEventListener('click',()=>changeQty(b.dataset.qtyPlus,1)));const total=lines.reduce((s,p)=>s+p.price*p.qty,0);document.querySelector('#subtotal').textContent=dz(total);document.querySelector('#total').textContent=dz(total)}
function changeQty(id,d){const line=cart.find(x=>String(x.id)===String(id)),p=products.find(x=>String(x.id)===String(id));line.qty+=d;if(line.qty<=0)cart=cart.filter(x=>String(x.id)!==String(id));if(line&&line.qty>p.stock)line.qty=p.stock;saveCart()}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelector('#'+id).classList.add('active');document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===id));document.body.classList.toggle('in-backoffice',id==='backoffice');window.scrollTo({top:0,behavior:'smooth'});if(id==='cart')renderCart()}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function renderInventory(){document.querySelector('#inventoryRows').innerHTML=products.map(p=>{const type=p.stock===0?'out':p.stock<6?'low':'ok',label=p.stock===0?'Rupture':p.stock<6?'Faible':'Disponible';return `<tr><td><b>${p.name}</b></td><td>${p.sku}</td><td>${dz(p.cost)}</td><td>${dz(p.price)}</td><td>${p.stock}</td><td><span class="stock-tag ${type}">${label}</span></td></tr>`}).join('');const low=products.filter(p=>p.stock<6);document.querySelector('#stockAlert').innerHTML=`<b>⚠ ${low.length} alertes :</b> ${low.map(p=>`${p.name} (${p.stock})`).join(' · ')}. Le bon de commande est prêt dans Fournisseurs.`;document.querySelector('#purchaseOrder').innerHTML=low.map(p=>`<div class="po-item"><span>${p.name}</span><b>${Math.max(12,25-p.stock)} unités</b></div>`).join('')}
function renderOrders(){const orders=[['BMS-1042','Fatima B.','Oran','12 380 DZD','À confirmer'],['BMS-1041','Sofiane K.','Alger','6 540 DZD','En préparation'],['BMS-1039','Nadia L.','Blida','18 900 DZD','Prête livraison']];document.querySelector('#ordersList').innerHTML=orders.map(o=>`<article class="order"><div><b>${o[0]}</b><p>${o[1]}</p></div><span>${o[2]}</span><b>${o[3]}</b><span class="stock-tag ${o[4]==='À confirmer'?'low':'ok'}">${o[4]}</span><button onclick="toast('Statut de ${o[0]} mis à jour')">Gérer</button></article>`).join('')}
function closeMobileNav(){document.querySelector('#mainNav').classList.remove('open');document.querySelector('#navOverlay').classList.add('hidden');document.querySelector('#menuToggle').setAttribute('aria-expanded','false')}
function openMobileNav(){document.querySelector('#mainNav').classList.add('open');document.querySelector('#navOverlay').classList.remove('hidden');document.querySelector('#menuToggle').setAttribute('aria-expanded','true')}
document.querySelector('#menuToggle').addEventListener('click',()=>document.querySelector('#mainNav').classList.contains('open')?closeMobileNav():openMobileNav());
document.querySelector('#navOverlay').addEventListener('click',closeMobileNav);
document.querySelectorAll('#mainNav .nav-link').forEach(btn=>btn.addEventListener('click',closeMobileNav));
document.querySelectorAll('[data-view]').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));document.querySelectorAll('[data-scroll]').forEach(btn=>btn.addEventListener('click',()=>document.querySelector('#'+btn.dataset.scroll).scrollIntoView({behavior:'smooth'})));document.querySelectorAll('.category').forEach(btn=>btn.addEventListener('click',()=>{selectedCategory=btn.dataset.category;document.querySelectorAll('.category').forEach(b=>b.classList.toggle('active',b===btn));renderProducts()}));document.querySelector('#searchInput').addEventListener('input',renderProducts);document.querySelector('#themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('bms-theme',document.body.classList.contains('dark')?'dark':'light')});document.querySelector('#languageToggle').addEventListener('click',()=>{const i=I18N_LANGS.indexOf(currentLang);setLanguage(I18N_LANGS[(i+1)%I18N_LANGS.length])});document.querySelector('#trackingForm').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#trackingResult').classList.remove('hidden')});document.querySelector('#checkoutBtn').addEventListener('click',()=>{if(!cart.length)return toast(t('toast.cartEmpty'));toast(t('toast.orderDemo'));cart=[];saveCart()});document.querySelectorAll('.admin-tab').forEach(btn=>btn.addEventListener('click',()=>{const panel=btn.dataset.panel;document.querySelectorAll('.admin-tab').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.admin-panel').forEach(x=>x.classList.toggle('active',x.id===panel));document.querySelector('#appTitle').textContent=btn.textContent.trim();document.querySelector('#appBreadcrumb').textContent='ESPACE PROPRIÉTAIRE'}));document.querySelectorAll('[data-panel-target]').forEach(b=>b.addEventListener('click',()=>document.querySelector(`.admin-tab[data-panel="${b.dataset.panelTarget}"]`).click()));document.querySelector('#addProduct').addEventListener('click',()=>toast('Formulaire d’ajout : à relier à la base de données dans la phase production.'));
const hasBackend=!!(window.BMS_CONFIG&&window.BMS_CONFIG.supabaseUrl&&(window.BMS_CONFIG.supabasePublishableKey||window.BMS_CONFIG.supabaseAnonKey));
if(localStorage.getItem('bms-theme')==='dark')document.body.classList.add('dark');
if(hasBackend){renderProductSkeleton();setTimeout(()=>{if(!window.bmsCatalogLoaded)renderProducts()},4000)}else{renderProducts()}
saveCart();renderInventory();renderOrders();
