const products=[
 {id:1,name:'Ensemble nuage en coton',age:'0-6',category:'0–6 mois',price:2890,cost:1450,stock:24,sku:'BMS-001',icon:'☁️',color:'#dceeff',badge:'Nouveau'},
 {id:2,name:'Doudou lapin douceur',age:'0-6',category:'Éveil & doudous',price:1950,cost:820,stock:5,sku:'BMS-002',icon:'🐰',color:'#ffe0e9',badge:'Best-seller'},
 {id:3,name:'Look mini aventurier',age:'6-18',category:'6–18 mois',price:4590,cost:2350,stock:0,sku:'BMS-003',icon:'🧢',color:'#e9e2cc',badge:'Été'},
 {id:4,name:'Coffret repas silicone',age:'6-18',category:'Repas',price:3750,cost:1800,stock:12,sku:'BMS-004',icon:'🥣',color:'#ffe4bb',badge:'Pratique'},
 {id:5,name:'Pyjama étoiles 2 pièces',age:'18-36',category:'18–36 mois',price:3490,cost:1620,stock:3,sku:'BMS-005',icon:'🌟',color:'#e5dbff',badge:'-15%'},
 {id:6,name:'Chaussures premiers pas',age:'18-36',category:'Chaussures',price:4250,cost:2190,stock:18,sku:'BMS-006',icon:'👟',color:'#d9f3e5',badge:'Confort'},
 {id:7,name:'Chapeau léger soleil',age:'season',category:'Collection été',price:1690,cost:690,stock:8,sku:'BMS-007',icon:'👒',color:'#ffe6b2',badge:'Été'},
 {id:8,name:'Tapis d’éveil safari',age:'0-6',category:'Éveil & doudous',price:8990,cost:4700,stock:2,sku:'BMS-008',icon:'🦁',color:'#d9eee3',badge:'Premium'}];
let cart=JSON.parse(localStorage.getItem('bms-cart')||'[]');let selectedCategory='all';
const dz=n=>new Intl.NumberFormat('fr-DZ').format(n)+' DZD';
function renderProducts(){const q=document.querySelector('#searchInput').value.toLowerCase();const list=products.filter(p=>(selectedCategory==='all'||p.age===selectedCategory||(selectedCategory==='season'&&p.age==='season'))&&p.name.toLowerCase().includes(q));document.querySelector('#productGrid').innerHTML=list.map(p=>`<article class="product"><div class="product-image" style="background:${p.color}"><span class="badge">${p.badge}</span>${p.icon}</div><div class="product-info"><p>${p.category}</p><h3>${p.name}</h3><div class="product-bottom"><b>${dz(p.price)}</b><button class="add-btn" onclick="addToCart(${p.id})" ${p.stock===0?'disabled title="Rupture de stock"':''}>${p.stock===0?'×':'+'}</button></div></div></article>`).join('')||'<p>Aucun produit trouvé.</p>'}
function addToCart(id){const p=products.find(p=>p.id===id),line=cart.find(x=>x.id===id);if(line){if(line.qty<p.stock)line.qty++}else cart.push({id,qty:1});saveCart();toast('Ajouté au panier ✨')}
function saveCart(){localStorage.setItem('bms-cart',JSON.stringify(cart));document.querySelector('#cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0);renderCart()}
function renderCart(){const holder=document.querySelector('#cartItems');if(!holder)return;const lines=cart.map(x=>({...products.find(p=>p.id===x.id),qty:x.qty}));holder.innerHTML=lines.length?lines.map(p=>`<article class="cart-item"><div class="cart-icon" style="background:${p.color}">${p.icon}</div><div><h3>${p.name}</h3><p>${dz(p.price)} · ${p.category}</p></div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${p.qty}</b><button onclick="changeQty(${p.id},1)">+</button></div></article>`).join(''):'<p>Votre panier est encore vide. Découvrez nos essentiels tout doux.</p>';const total=lines.reduce((s,p)=>s+p.price*p.qty,0);document.querySelector('#subtotal').textContent=dz(total);document.querySelector('#total').textContent=dz(total)}
function changeQty(id,d){const line=cart.find(x=>x.id===id),p=products.find(x=>x.id===id);line.qty+=d;if(line.qty<=0)cart=cart.filter(x=>x.id!==id);if(line&&line.qty>p.stock)line.qty=p.stock;saveCart()}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelector('#'+id).classList.add('active');document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='cart')renderCart()}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function renderInventory(){document.querySelector('#inventoryRows').innerHTML=products.map(p=>{const type=p.stock===0?'out':p.stock<6?'low':'ok',label=p.stock===0?'Rupture':p.stock<6?'Faible':'Disponible';return `<tr><td><b>${p.name}</b></td><td>${p.sku}</td><td>${dz(p.cost)}</td><td>${dz(p.price)}</td><td>${p.stock}</td><td><span class="stock-tag ${type}">${label}</span></td></tr>`}).join('');const low=products.filter(p=>p.stock<6);document.querySelector('#stockAlert').innerHTML=`<b>⚠ ${low.length} alertes :</b> ${low.map(p=>`${p.name} (${p.stock})`).join(' · ')}. Le bon de commande est prêt dans Fournisseurs.`;document.querySelector('#purchaseOrder').innerHTML=low.map(p=>`<div class="po-item"><span>${p.name}</span><b>${Math.max(12,25-p.stock)} unités</b></div>`).join('')}
function renderOrders(){const orders=[['BMS-1042','Fatima B.','Oran','12 380 DZD','À confirmer'],['BMS-1041','Sofiane K.','Alger','6 540 DZD','En préparation'],['BMS-1039','Nadia L.','Blida','18 900 DZD','Prête livraison']];document.querySelector('#ordersList').innerHTML=orders.map(o=>`<article class="order"><div><b>${o[0]}</b><p>${o[1]}</p></div><span>${o[2]}</span><b>${o[3]}</b><span class="stock-tag ${o[4]==='À confirmer'?'low':'ok'}">${o[4]}</span><button onclick="toast('Statut de ${o[0]} mis à jour')">Gérer</button></article>`).join('')}
document.querySelectorAll('[data-view]').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));document.querySelectorAll('[data-scroll]').forEach(btn=>btn.addEventListener('click',()=>document.querySelector('#'+btn.dataset.scroll).scrollIntoView({behavior:'smooth'})));document.querySelectorAll('.category').forEach(btn=>btn.addEventListener('click',()=>{selectedCategory=btn.dataset.category;document.querySelectorAll('.category').forEach(b=>b.classList.toggle('active',b===btn));renderProducts()}));document.querySelector('#searchInput').addEventListener('input',renderProducts);document.querySelector('#themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('bms-theme',document.body.classList.contains('dark')?'dark':'light')});document.querySelector('#languageToggle').addEventListener('click',e=>{const a=['FR','عر','EN','DZ'];e.target.textContent=a[(a.indexOf(e.target.textContent)+1)%a.length];toast('Langue de démonstration modifiée. Les traductions complètes seront reliées au backend.')});document.querySelector('#trackingForm').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#trackingResult').classList.remove('hidden')});document.querySelector('#checkoutBtn').addEventListener('click',()=>{if(!cart.length)return toast('Votre panier est vide.');toast('Commande COD enregistrée — nous vous contacterons !');cart=[];saveCart()});document.querySelectorAll('.admin-tab').forEach(btn=>btn.addEventListener('click',()=>{const panel=btn.dataset.panel;document.querySelectorAll('.admin-tab').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.admin-panel').forEach(x=>x.classList.toggle('active',x.id===panel));document.querySelector('#appTitle').textContent=btn.textContent.trim();document.querySelector('#appBreadcrumb').textContent='ESPACE PROPRIÉTAIRE'}));document.querySelectorAll('[data-panel-target]').forEach(b=>b.addEventListener('click',()=>document.querySelector(`.admin-tab[data-panel="${b.dataset.panelTarget}"]`).click()));document.querySelector('#addProduct').addEventListener('click',()=>toast('Formulaire d’ajout : à relier à la base de données dans la phase production.'));
if(localStorage.getItem('bms-theme')==='dark')document.body.classList.add('dark');renderProducts();saveCart();renderInventory();renderOrders();
