/* Photos, modification et suppression de produits — Supabase Storage. */
(function(){
  const oldForm=document.querySelector('#productForm');
  const form=oldForm.cloneNode(true);oldForm.replaceWith(form);
  const publishLabel=document.querySelector('#productPublished').closest('label');
  publishLabel.insertAdjacentHTML('beforebegin','<label class="upload-zone">📷 <span>Ajouter ou remplacer des photos</span><input id="productPhotos" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><div id="imageManager" class="image-manager"></div>');
  const q=id=>document.querySelector(id), modal=q('#productModal'), message=q('#productMessage'), photos=q('#productPhotos'), manager=q('#imageManager');
  let editingId=null, existingImages=[];
  const esc=s=>String(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const media=(url,name='')=>url?`<img class="inventory-image" src="${url}" alt="${esc(name)}">`:'';
  const map=p=>({id:p.id,name:p.name_fr,name_ar:p.name_ar,name_en:p.name_en,age:p.age_group||'0-6',category:p.age_group?`${p.age_group} mois`:'Essentiels',price:Number(p.sale_price),cost:Number(p.purchase_price||0),stock:p.stock_quantity,sku:p.sku,image_url:p.image_url,icon:p.image_url?`<img src="${p.image_url}" alt="${esc(p.name_fr)}">`:'🧸',color:'#ffe7ef',badge:p.seasonal?'Saison':'Disponible',published:p.published,reorder:p.reorder_level});
  function drawImages(){manager.innerHTML=existingImages.map(x=>`<div class="image-thumb"><img src="${x.public_url}" alt="Photo produit"><button type="button" data-delete-image="${x.id}" title="Supprimer">×</button></div>`).join('')+Array.from(photos.files||[]).map(file=>`<div class="image-thumb"><img src="${URL.createObjectURL(file)}" alt="Nouvelle photo"></div>`).join('');manager.querySelectorAll('[data-delete-image]').forEach(btn=>btn.addEventListener('click',()=>deleteImage(btn.dataset.deleteImage)))}
  function reset(){editingId=null;existingImages=[];form.reset();q('#productReorder').value=5;q('#productPublished').checked=true;q('#productTitle').textContent='Ajouter un produit';drawImages()}
  function close(){modal.classList.add('hidden');message.textContent='';reset()}
  async function loadAll(){if(!window.bmsDb)return;const {data,error}=await window.bmsDb.from('products').select('*').order('created_at',{ascending:false});if(error)return toast('Impossible de charger le stock : '+error.message);products.splice(0,products.length,...data.map(map));renderProducts();renderInventory()}
  async function loadPublicMedia(){if(!window.bmsDb)return;const {data}=await window.bmsDb.from('catalog_products').select('id,image_url,name_fr');if(data){data.forEach(row=>{const p=products.find(x=>x.id===row.id);if(p&&row.image_url){p.image_url=row.image_url;p.icon=`<img src="${row.image_url}" alt="${esc(row.name_fr)}">`}});renderProducts()}}
  renderInventory=function(){const low=products.filter(p=>p.stock<6);q('#stockAlert').innerHTML=`<b>⚠ ${low.length} alertes :</b> ${low.map(p=>`${esc(p.name)} (${p.stock})`).join(' · ')}.`;q('#inventoryRows').innerHTML=products.map(p=>{const type=p.stock===0?'out':p.stock<6?'low':'ok',label=p.stock===0?'Rupture':p.stock<6?'Faible':'Disponible';return `<tr><td>${media(p.image_url,p.name)}<b>${esc(p.name)}</b></td><td>${esc(p.sku)}</td><td>${dz(p.cost)}</td><td>${dz(p.price)}</td><td>${p.stock}</td><td><span class="stock-tag ${type}">${label}</span></td><td><div class="row-actions"><button class="edit-product" data-edit="${p.id}">Modifier</button><button class="delete-product" data-remove="${p.id}">Supprimer</button></div></td></tr>`}).join('');q('#inventoryRows').querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>editProduct(b.dataset.edit)));q('#inventoryRows').querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>removeProduct(b.dataset.remove)));const poHolder=q('#purchaseOrder');if(poHolder)poHolder.innerHTML=low.map(p=>`<div class="po-item"><span>${esc(p.name)}</span><b>${Math.max(12,25-p.stock)} unités</b></div>`).join('')||'<p class="pos-empty">Aucune alerte de stock pour le moment.</p>'};
  q('.admin-tab[data-panel="inventory"]').addEventListener('click',async()=>{await loadAll();await loadPublicMedia()});
  window.bmsRefreshInventory=async()=>{if(document.querySelector('#inventory')?.classList.contains('active')){await loadAll();await loadPublicMedia()}};
  photos.addEventListener('change',drawImages);q('#closeProduct').addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});
  async function editProduct(id){if(!window.bmsDb)return;const p=products.find(x=>x.id===id);if(!p)return;editingId=id;q('#productTitle').textContent='Modifier le produit';q('#productSku').value=p.sku;q('#productName').value=p.name;q('#productNameAr').value=p.name_ar||'';q('#productNameEn').value=p.name_en||'';q('#productAge').value=p.age;q('#productCost').value=p.cost;q('#productPrice').value=p.price;q('#productStock').value=p.stock;q('#productReorder').value=p.reorder||5;q('#productPublished').checked=p.published;photos.value='';const {data}=await window.bmsDb.from('product_images').select('*').eq('product_id',id).order('position');existingImages=data||[];drawImages();modal.classList.remove('hidden')}
  async function deleteImage(id){if(!window.bmsDb||!confirm('Supprimer définitivement cette photo ?'))return;const image=existingImages.find(x=>x.id===id);if(!image)return;await window.bmsDb.storage.from('product-images').remove([image.storage_path]);const {error}=await window.bmsDb.from('product_images').delete().eq('id',id);if(error)return toast('Erreur photo : '+error.message);existingImages=existingImages.filter(x=>x.id!==id);const first=existingImages[0]?.public_url||null;await window.bmsDb.from('products').update({image_url:first}).eq('id',editingId);drawImages();await loadAll()}
  async function removeProduct(id){if(!window.bmsDb||!confirm('Supprimer ce produit et toutes ses photos ?'))return;const {data:images}=await window.bmsDb.from('product_images').select('storage_path').eq('product_id',id);if(images?.length)await window.bmsDb.storage.from('product-images').remove(images.map(x=>x.storage_path));const {error}=await window.bmsDb.from('products').delete().eq('id',id);if(error)return toast('Suppression refusée : '+error.message);await loadAll();toast('Produit supprimé.');}
  async function uploadFiles(productId){const files=Array.from(photos.files||[]);let firstUrl=null;for(let i=0;i<files.length;i++){const file=files[i],safe=file.name.toLowerCase().replace(/[^a-z0-9._-]/g,'-'),path=`${productId}/${crypto.randomUUID()}-${safe}`;const {error:uploadError}=await window.bmsDb.storage.from('product-images').upload(path,file,{contentType:file.type});if(uploadError)throw uploadError;const {data:urlData}=window.bmsDb.storage.from('product-images').getPublicUrl(path);const url=urlData.publicUrl;if(!firstUrl)firstUrl=url;const {error:dbError}=await window.bmsDb.from('product_images').insert({product_id:productId,storage_path:path,public_url:url,position:existingImages.length+i});if(dbError)throw dbError}return firstUrl}
  form.addEventListener('submit',async e=>{e.preventDefault();if(!window.bmsDb)return;message.textContent='Enregistrement…';const item={sku:q('#productSku').value.trim(),name_fr:q('#productName').value.trim(),name_ar:q('#productNameAr').value.trim()||null,name_en:q('#productNameEn').value.trim()||null,age_group:q('#productAge').value,purchase_price:Number(q('#productCost').value),sale_price:Number(q('#productPrice').value),stock_quantity:Number(q('#productStock').value),reorder_level:Number(q('#productReorder').value),published:q('#productPublished').checked};const wasEditing=Boolean(editingId);let id=editingId;let error;if(id)({error}=await window.bmsDb.from('products').update(item).eq('id',id));else{const result=await window.bmsDb.from('products').insert(item).select('id').single();error=result.error;id=result.data?.id}if(error){message.textContent='Erreur : '+error.message;return}try{const first=await uploadFiles(id);if(first)await window.bmsDb.from('products').update({image_url:first}).eq('id',id)}catch(err){message.textContent='Produit enregistré, mais photo refusée : '+err.message;return}close();await loadAll();await loadPublicMedia();toast(wasEditing?'Produit modifié.':'Produit ajouté avec succès.');});
  loadPublicMedia();
})();
